package com.tecgurus.whattimeisit.data.layer.model;

// Generated Jul 3, 2013 8:59:44 PM by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * ClienteBancoViewId generated by hbm2java
 */
@Embeddable
public class ClienteBancoViewId implements java.io.Serializable {

	private int idCliente;
	private String clienteNombre;
	private String appMaterno;
	private String appPaterno;
	private int clienteEdad;
	private int idBanco;
	private String bancoNombre;

	public ClienteBancoViewId() {
	}

	public ClienteBancoViewId(int idCliente, String clienteNombre,
			String appMaterno, String appPaterno, int clienteEdad, int idBanco,
			String bancoNombre) {
		this.idCliente = idCliente;
		this.clienteNombre = clienteNombre;
		this.appMaterno = appMaterno;
		this.appPaterno = appPaterno;
		this.clienteEdad = clienteEdad;
		this.idBanco = idBanco;
		this.bancoNombre = bancoNombre;
	}

	@Column(name = "idCliente", nullable = false)
	public int getIdCliente() {
		return this.idCliente;
	}

	public void setIdCliente(int idCliente) {
		this.idCliente = idCliente;
	}

	@Column(name = "clienteNombre", nullable = false, length = 50)
	public String getClienteNombre() {
		return this.clienteNombre;
	}

	public void setClienteNombre(String clienteNombre) {
		this.clienteNombre = clienteNombre;
	}

	@Column(name = "appMaterno", nullable = false, length = 50)
	public String getAppMaterno() {
		return this.appMaterno;
	}

	public void setAppMaterno(String appMaterno) {
		this.appMaterno = appMaterno;
	}

	@Column(name = "appPaterno", nullable = false, length = 30)
	public String getAppPaterno() {
		return this.appPaterno;
	}

	public void setAppPaterno(String appPaterno) {
		this.appPaterno = appPaterno;
	}

	@Column(name = "clienteEdad", nullable = false)
	public int getClienteEdad() {
		return this.clienteEdad;
	}

	public void setClienteEdad(int clienteEdad) {
		this.clienteEdad = clienteEdad;
	}

	@Column(name = "idBanco", nullable = false)
	public int getIdBanco() {
		return this.idBanco;
	}

	public void setIdBanco(int idBanco) {
		this.idBanco = idBanco;
	}

	@Column(name = "bancoNombre", nullable = false, length = 50)
	public String getBancoNombre() {
		return this.bancoNombre;
	}

	public void setBancoNombre(String bancoNombre) {
		this.bancoNombre = bancoNombre;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ClienteBancoViewId))
			return false;
		ClienteBancoViewId castOther = (ClienteBancoViewId) other;

		return (this.getIdCliente() == castOther.getIdCliente())
				&& ((this.getClienteNombre() == castOther.getClienteNombre()) || (this
						.getClienteNombre() != null
						&& castOther.getClienteNombre() != null && this
						.getClienteNombre()
						.equals(castOther.getClienteNombre())))
				&& ((this.getAppMaterno() == castOther.getAppMaterno()) || (this
						.getAppMaterno() != null
						&& castOther.getAppMaterno() != null && this
						.getAppMaterno().equals(castOther.getAppMaterno())))
				&& ((this.getAppPaterno() == castOther.getAppPaterno()) || (this
						.getAppPaterno() != null
						&& castOther.getAppPaterno() != null && this
						.getAppPaterno().equals(castOther.getAppPaterno())))
				&& (this.getClienteEdad() == castOther.getClienteEdad())
				&& (this.getIdBanco() == castOther.getIdBanco())
				&& ((this.getBancoNombre() == castOther.getBancoNombre()) || (this
						.getBancoNombre() != null
						&& castOther.getBancoNombre() != null && this
						.getBancoNombre().equals(castOther.getBancoNombre())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getIdCliente();
		result = 37
				* result
				+ (getClienteNombre() == null ? 0 : this.getClienteNombre()
						.hashCode());
		result = 37
				* result
				+ (getAppMaterno() == null ? 0 : this.getAppMaterno()
						.hashCode());
		result = 37
				* result
				+ (getAppPaterno() == null ? 0 : this.getAppPaterno()
						.hashCode());
		result = 37 * result + this.getClienteEdad();
		result = 37 * result + this.getIdBanco();
		result = 37
				* result
				+ (getBancoNombre() == null ? 0 : this.getBancoNombre()
						.hashCode());
		return result;
	}

}
