package com.tecgurus.whattimeisit.data.layer.model;

// Generated Jul 3, 2013 8:59:44 PM by Hibernate Tools 4.0.0

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * ClienteCuentaView generated by hbm2java
 */
@Entity
@Table(name = "ClienteCuentaView")
public class ClienteCuentaView implements java.io.Serializable {

	private ClienteCuentaViewId id;

	public ClienteCuentaView() {
	}

	public ClienteCuentaView(ClienteCuentaViewId id) {
		this.id = id;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "idCliente", column = @Column(name = "idCliente", nullable = false)),
			@AttributeOverride(name = "appMaterno", column = @Column(name = "appMaterno", nullable = false, length = 50)),
			@AttributeOverride(name = "appPaterno", column = @Column(name = "appPaterno", nullable = false, length = 30)),
			@AttributeOverride(name = "idBanco", column = @Column(name = "idBanco", nullable = false)),
			@AttributeOverride(name = "nombreBanco", column = @Column(name = "nombreBanco", nullable = false, length = 50)),
			@AttributeOverride(name = "idCuenta", column = @Column(name = "idCuenta", nullable = false)),
			@AttributeOverride(name = "numeroCuenta", column = @Column(name = "numeroCuenta", nullable = false)) })
	public ClienteCuentaViewId getId() {
		return this.id;
	}

	public void setId(ClienteCuentaViewId id) {
		this.id = id;
	}

}
