package com.tecgurus.whattimeisit.data.layer.model;

// Generated Jul 3, 2013 8:59:44 PM by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * ClienteCuentaViewId generated by hbm2java
 */
@Embeddable
public class ClienteCuentaViewId implements java.io.Serializable {

	private int idCliente;
	private String appMaterno;
	private String appPaterno;
	private int idBanco;
	private String nombreBanco;
	private int idCuenta;
	private int numeroCuenta;

	public ClienteCuentaViewId() {
	}

	public ClienteCuentaViewId(int idCliente, String appMaterno,
			String appPaterno, int idBanco, String nombreBanco, int idCuenta,
			int numeroCuenta) {
		this.idCliente = idCliente;
		this.appMaterno = appMaterno;
		this.appPaterno = appPaterno;
		this.idBanco = idBanco;
		this.nombreBanco = nombreBanco;
		this.idCuenta = idCuenta;
		this.numeroCuenta = numeroCuenta;
	}

	@Column(name = "idCliente", nullable = false)
	public int getIdCliente() {
		return this.idCliente;
	}

	public void setIdCliente(int idCliente) {
		this.idCliente = idCliente;
	}

	@Column(name = "appMaterno", nullable = false, length = 50)
	public String getAppMaterno() {
		return this.appMaterno;
	}

	public void setAppMaterno(String appMaterno) {
		this.appMaterno = appMaterno;
	}

	@Column(name = "appPaterno", nullable = false, length = 30)
	public String getAppPaterno() {
		return this.appPaterno;
	}

	public void setAppPaterno(String appPaterno) {
		this.appPaterno = appPaterno;
	}

	@Column(name = "idBanco", nullable = false)
	public int getIdBanco() {
		return this.idBanco;
	}

	public void setIdBanco(int idBanco) {
		this.idBanco = idBanco;
	}

	@Column(name = "nombreBanco", nullable = false, length = 50)
	public String getNombreBanco() {
		return this.nombreBanco;
	}

	public void setNombreBanco(String nombreBanco) {
		this.nombreBanco = nombreBanco;
	}

	@Column(name = "idCuenta", nullable = false)
	public int getIdCuenta() {
		return this.idCuenta;
	}

	public void setIdCuenta(int idCuenta) {
		this.idCuenta = idCuenta;
	}

	@Column(name = "numeroCuenta", nullable = false)
	public int getNumeroCuenta() {
		return this.numeroCuenta;
	}

	public void setNumeroCuenta(int numeroCuenta) {
		this.numeroCuenta = numeroCuenta;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ClienteCuentaViewId))
			return false;
		ClienteCuentaViewId castOther = (ClienteCuentaViewId) other;

		return (this.getIdCliente() == castOther.getIdCliente())
				&& ((this.getAppMaterno() == castOther.getAppMaterno()) || (this
						.getAppMaterno() != null
						&& castOther.getAppMaterno() != null && this
						.getAppMaterno().equals(castOther.getAppMaterno())))
				&& ((this.getAppPaterno() == castOther.getAppPaterno()) || (this
						.getAppPaterno() != null
						&& castOther.getAppPaterno() != null && this
						.getAppPaterno().equals(castOther.getAppPaterno())))
				&& (this.getIdBanco() == castOther.getIdBanco())
				&& ((this.getNombreBanco() == castOther.getNombreBanco()) || (this
						.getNombreBanco() != null
						&& castOther.getNombreBanco() != null && this
						.getNombreBanco().equals(castOther.getNombreBanco())))
				&& (this.getIdCuenta() == castOther.getIdCuenta())
				&& (this.getNumeroCuenta() == castOther.getNumeroCuenta());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getIdCliente();
		result = 37
				* result
				+ (getAppMaterno() == null ? 0 : this.getAppMaterno()
						.hashCode());
		result = 37
				* result
				+ (getAppPaterno() == null ? 0 : this.getAppPaterno()
						.hashCode());
		result = 37 * result + this.getIdBanco();
		result = 37
				* result
				+ (getNombreBanco() == null ? 0 : this.getNombreBanco()
						.hashCode());
		result = 37 * result + this.getIdCuenta();
		result = 37 * result + this.getNumeroCuenta();
		return result;
	}

}
