package com.tecgurus.whattimeisit.data.layer.model;

// Generated Jul 3, 2013 8:59:44 PM by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Cuenta generated by hbm2java
 */
@Entity
@Table(name = "Cuenta")
public class Cuenta implements java.io.Serializable {

	private Integer idCuenta;
	private int idCliente;
	private int idTipoCuenta;
	private int numeroCuenta;

	public Cuenta() {
	}

	public Cuenta(int idCliente, int idTipoCuenta, int numeroCuenta) {
		this.idCliente = idCliente;
		this.idTipoCuenta = idTipoCuenta;
		this.numeroCuenta = numeroCuenta;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "idCuenta", unique = true, nullable = false)
	public Integer getIdCuenta() {
		return this.idCuenta;
	}

	public void setIdCuenta(Integer idCuenta) {
		this.idCuenta = idCuenta;
	}

	@Column(name = "idCliente", nullable = false)
	public int getIdCliente() {
		return this.idCliente;
	}

	public void setIdCliente(int idCliente) {
		this.idCliente = idCliente;
	}

	@Column(name = "idTipoCuenta", nullable = false)
	public int getIdTipoCuenta() {
		return this.idTipoCuenta;
	}

	public void setIdTipoCuenta(int idTipoCuenta) {
		this.idTipoCuenta = idTipoCuenta;
	}

	@Column(name = "numeroCuenta", nullable = false)
	public int getNumeroCuenta() {
		return this.numeroCuenta;
	}

	public void setNumeroCuenta(int numeroCuenta) {
		this.numeroCuenta = numeroCuenta;
	}

}
