package com.tecgurus.whattimeisit.data.layer.model;

// Generated Jul 1, 2013 12:54:47 AM by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * TipoMovimiento generated by hbm2java
 */
@Entity
@Table(name = "TipoMovimiento")
public class TipoMovimiento implements java.io.Serializable {

	private Integer idTipoMovimiento;
	private String nombre;

	public TipoMovimiento() {
	}

	public TipoMovimiento(String nombre) {
		this.nombre = nombre;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "idTipoMovimiento", unique = true, nullable = false)
	public Integer getIdTipoMovimiento() {
		return this.idTipoMovimiento;
	}

	public void setIdTipoMovimiento(Integer idTipoMovimiento) {
		this.idTipoMovimiento = idTipoMovimiento;
	}

	@Column(name = "nombre", nullable = false, length = 30)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

}
