package com.tecgurus.whattimeisit.data.layer.model;

// Generated Jul 1, 2013 12:54:47 AM by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * TipoCuenta generated by hbm2java
 */
@Entity
@Table(name = "TipoCuenta")
public class TipoCuenta implements java.io.Serializable {

	private Integer idTipoCuenta;
	private String nombre;

	public TipoCuenta() {
	}

	public TipoCuenta(String nombre) {
		this.nombre = nombre;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "idTipoCuenta", unique = true, nullable = false)
	public Integer getIdTipoCuenta() {
		return this.idTipoCuenta;
	}

	public void setIdTipoCuenta(Integer idTipoCuenta) {
		this.idTipoCuenta = idTipoCuenta;
	}

	@Column(name = "nombre", nullable = false, length = 20)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

}
